; auto-generated by hexarchy theme
; will be overwritten by theme system

[general]
bars = 0
framerate = 60
sensitivity = 100

[input]
method = pulse

[output]
method = noncurses

[colors]
gradient = 1
gradient_count = 6
gradient_color_1 = '{{ background }}'
gradient_color_2 = '{{ blue }}'
gradient_color_3 = '{{ cyan }}'
gradient_color_4 = '{{ green }}'
gradient_color_5 = '{{ yellow }}'
gradient_color_6 = '{{ red }}'

[smoothing]
integral = 0.5
monstercat = 1
waves = 0.1
